# See: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-security:
        applies-to: security-updates
        patterns: ["*"]
      go:
        applies-to: version-updates
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-security:
        applies-to: security-updates
        patterns: ["*"]
      actions:
        applies-to: version-updates
        patterns: ["*"]
