linters:
  disable-all: true
  enable:
    # Defaults:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional:
    - gocritic
    - gofmt
    - goimports
    - gosec
    - lll
    - misspell
    - nolintlint

linters-settings:
  errcheck:
    check-type-assertions: true
  goimports:
    local-prefixes: github.com/upsun/whatsun
  nolintlint:
    allow-unused: false
    require-specific: true
  prealloc:
    for-loops: true
