version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    nolintlint:
      require-specific: true
      allow-unused: false
    prealloc:
      for-loops: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/upsun/whatsun
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
