# Analyze frameworks. Note, these are just examples.
# TODO complete these rules
frameworks:
  max_depth: 5
  max_nested_depth: 1
  rules:
    drupal:
      when: dep.has("php", "drupal/core") || dep.has("php", "drupal/core-recommended")
      then: drupal
      with:
        major_version: version.parse(dep.getVersion("php", "drupal/core")).major
      exclusive: true
      group: php

    # The drupal/drupal package represents Drupal 7.
    drupal7-composer:
      when: dep.has("php", "drupal/drupal")
      then: drupal
      with:
        major_version: version.parse(dep.getVersion("php", "drupal/drupal")).major
      exclusive: true
      group: php

    drupal-direct:
      when: file.exists("index.php") && file.contains("index.php", "drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);")
      then: drupal
      group: php

    symfony-project:
      when: dep.has("php", "symfony/*") && json.queryString(file.read("composer.json"), ".type") == "project"
      maybe: [symfony]
      group: php

    symfony-framework:
      when: dep.has("php", "symfony/framework-bundle")
      then: symfony
      with:
        major_version: version.parse(dep.getVersion("php", "symfony/framework-bundle")).major
      group: php
      exclusive: true

    laravel-framework:
      when: dep.has("php", "laravel/framework")
      then: laravel
      with:
        major_version: version.parse(dep.getVersion("php", "laravel/framework")).major
      group: php
      exclusive: true

    express:
      when: dep.has("js", "express")
      then: express
      with:
        version: version.parse(dep.getVersion("js", "express"))
      group: js

    gatsby:
      when: file.exists("gatsby-config.js") || dep.has("js", "gatsby")
      then: gatsby
      with:
        version: version.parse(dep.getVersion("js", "gatsby"))
      group: js
      exclusive: true

    strapi:
      when: file.exists("strapi-config.json") || dep.has("js", "@strapi/strapi")
      then: strapi
      with:
        version: version.parse(dep.getVersion("js", "@strapi/strapi"))
      group: js
      exclusive: true

    magento:
      when: dep.has("php", "magento/magento-composer-installer")
      then: magento
      exclusive: true
      group: php

    gin:
      when: dep.has("go", "github.com/gin-gonic/gin")
      then: gin
      with:
        version: version.parse(dep.getVersion("go", "github.com/gin-gonic/gin"))
      group: go

    flask:
      when: dep.has("python", "flask")
      then: flask
      group: python

    pyramid:
      when: dep.has("python", "pyramid")
      then: pyramid
      group: python
