# Analyze frameworks. Note, these are just examples.
# TODO complete these rules
frameworks:
  rules:
    - name: drupal
      when: composer.requires("drupal/core") || composer.requires("drupal/core-recommended")
      then: drupal
      with:
        major_version: version.parse(composer.lockedVersion("drupal/core")).major
      exclusive: true
      group: php

    # The drupal/drupal package represents Drupal 7.
    - name: drupal7-composer
      when: composer.requires("drupal/drupal")
      then: drupal
      with:
        major_version: version.parse(composer.lockedVersion("drupal/drupal")).major
      exclusive: true
      group: php

    - name: drupal-direct
      when: file.exists("index.php") && file.contains("index.php", "drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);")
      then: drupal
      group: php

    - name: symfony-project
      when: composer.requires("symfony/*") && json.queryString(file.read("composer.json"), ".type") == "project"
      maybe: [symfony]
      group: php

    - name: symfony-framework
      when: composer.requires("symfony/framework-bundle")
      then: symfony
      with:
        major_version: version.parse(composer.lockedVersion("symfony/framework-bundle")).major
      group: php
      exclusive: true

    - name: laravel-framework
      when: composer.requires("laravel/framework")
      then: laravel
      with:
        major_version: version.parse(composer.lockedVersion("laravel/framework")).major
      group: php
      exclusive: true

    - name: express
      when: npm.depends("express")
      then: express
      group: js

    - name: gatsby
      when: file.exists("gatsby-config.js") || npm.depends("gatsby")
      then: gatsby
      group: js
      exclusive: true

    - name: gatsby
      when: file.exists("strapi-config.json") || npm.depends("@strapi/strapi")
      then: strapi
      group: js
      exclusive: true

    - name: magento
      when: composer.requires("magento/magento-composer-installer")
      then: magento
      exclusive: true
      group: php
