# Analyze package managers.
package_managers:
  rules:
    npm-lockfile:
      when: fs.fileExists("package-lock.json")
      then: npm
      group: js
    yarn-lockfile:
      when: fs.fileExists("yarn.lock")
      then: yarn
      group: js
    meteor:
      when: fs.fileExists(".meteor/packages")
      then: meteor
      group: js
    pnpm:
      when: fs.fileExists("pnpm-lock.yaml") || fs.fileExists("pnpm-workspace.yaml")
      then: pnpm
      group: js
    bun:
      when: fs.fileExists("bun.lock") || fs.fileExists("bun.lockb")
      then: bun
      group: js
    deno:
      when: fs.fileExists("deno.json") || fs.fileExists("deno.lock")
      then: deno
      group: js
      read_files: [deno.json]
    js-packages:
      when: fs.fileExists("package.json")
      maybe: [npm, pnpm, yarn, bun]
      group: js
      read_files: [package.json]

    composer:
      when: fs.fileExists("composer.json")
      then: composer
      with:
        php_version: jq(fs.read("composer.json"), ".require.php")
      ignore:
        - modules/ # Drupal modules
        - Magento/ # Magento plugins and themes
      group: php
      read_files: [composer.json]

    pip:
      when: fs.fileExists("requirements.txt")
      then: pip
      group: python

    pipenv:
      when: fs.fileExists("Pipfile")
      then: pipenv
      group: python

    pyproject:
      when: fs.fileExists("pyproject.toml")
      maybe: [poetry, pip, uv]
      group: python

    poetry:
      when: fs.fileExists("poetry.lock")
      then: poetry
      group: python

    bundler:
      when: fs.glob("Gemfile*").size() > 0
      then: bundler
      group: ruby

    gomod:
      when: fs.fileExists("go.mod") || fs.fileExists("go.sum")
      then: gomod
      group: go

    cargo:
      when: fs.fileExists("Cargo.toml")
      then: cargo
      group: rust

    maven:
      when: fs.fileExists("pom.xml")
      then: maven
      group: java

    gradle:
      when: fs.fileExists("build.gradle") || fs.fileExists("build.gradle.kts")
      then: gradle
      group: java

    nuget:
      when: fs.fileExists("packages.config")
      then: nuget
      group: dotnet

    msbuild:
      when: fs.glob("*.csproj").size() > 0
      then: msbuild
      group: dotnet

    mix:
      when: fs.fileExists("mix.exs")
      then: mix
      group: elixir

    quicklisp:
      when: fs.isDir("quicklisp")
      then: quicklisp
      group: lisp
